// Generated by https://quicktype.io

export interface UserResponse {
  _id: string;
  uid: string;
  email: string;
  googleId: string;
  boards: Board[];
  __v: number;
}

export interface Board {
  _id: string;
  name: string;
  createdAt: number;
  indexOrder: number;
  color: string;
  tickets: Ticket[];
}

export interface Ticket {
  _id: string;
  description: string;
  createdAt: number;
  categoryId: string;
  content: string;
  color: string;
}
